---
- name: Create file inside container
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create index.txt
      copy:
        dest: "/tmp/index.txt"
        content: |
          Hello, World!
          A change is coming!

    - name: Display file content
      command: cat /tmp/index.txt
      register: output

    - name: Show output
      debug:
        var: output.stdout
